apiVersion: v1
kind: Pod
metadata:
  labels:
    name: default
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: false
spec:
  imagePullSecrets:
  - name: regsecret
  tolerations:
  - key: tooling.nextiva.io
    operator: Equal
    value: jenkins
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicatedgroup
            operator: In
            values:
            - jenkins-slave