apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    name: default
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: false
spec:
  imagePullSecrets:
  - name: regsecret
  hostAliases:
  - ip: "192.168.103.218"
    hostnames:
    - "quote.rc.nextiva.xyz"
  - ip: "10.80.10.13"
    hostnames:
    - "jira.nextiva.xyz"
  imagePullSecrets:
  - name: regsecret
  tolerations:
  - key: tooling.nextiva.io
    operator: Equal
    value: jenkins
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - jenkins-slave
  volumes:
  - name: m2cache
    hostPath:
      path: /opt/m2
  - name: npmcache
    hostPath:
      path: /opt/npmcache
  - name: yarncache
    hostPath:
      path: /opt/yarncache
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock