apiVersion: v1
kind: Pod
metadata:
  labels:
    name: default
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: false
spec:
  hostAliases:
  - ip: "192.168.103.218"
    hostnames:
    - "quote.rc.nextiva.xyz"
  - ip: "10.80.10.13"
    hostnames:
    - "jira.nextiva.xyz"
  imagePullSecrets:
  - name: regsecret
  tolerations:
  - key: tooling.nextiva.io
    operator: Equal
    value: jenkins
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicatedgroup
            operator: In
            values:
            - jenkins-slave